### Request a token from Keycloak
# @name getToken
POST https://kc.tommyneumaier.at/realms/2425-5bhitm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=leomail&client_secret={{client_secret}}&username={{username}}&password={{password}}

###
GET http://localhost:8080/test/authtest
Content-Type: */*
Authorization: Bearer {{getToken.response.body.access_token}}

###
GET https://kc.tommyneumaier.at/realms/2425-5bhitm/protocol/openid-connect/userinfo
#Authorization:

###
GET https://kc.tommyneumaier.at/admin/realms/2425-5bhitm/users
#Authorization: