### SEND EMAIL BY TEMPLATE
POST http://localhost:8080/mail/sendByTemplate
Content-Type: application/json

{
  "templateId": 1,
  "personalized": true,
  "receiver": {
    "groups": [],
    "contacts": [1,2]
  }
}