stages:
  - build
  - test
  - deploy

variables:
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY
  SSH_USER: deployment
  SSH_HOST: tommyneumaier.at
  APP_NAME: leomail-backend-1.0-SNAPSHOT

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
  - chmod 600 ~/.ssh/id_ed25519
  - ssh-add ~/.ssh/id_ed25519
  - cat ~/.ssh/id_ed25519
  - ssh-keygen -y -f ~/.ssh/id_ed25519 

build:
  stage: build
  image: maven
  script:
    - ls -la
    - cd app/leomail-backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - app/leomail-backend/target/*.jar

test:
  stage: test
  image: maven
  script:
    - cd app/leomail-backend
    - mvn test

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk update && apk add openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/deployment_key
    - chmod 600 ~/.ssh/deployment_key
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/deployment_key
    # Add the host key of the remote server to known_hosts
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - ls -a app/leomail-backend/target
    # Verify SSH connection
    - ssh -vvv $SSH_USER@$SSH_HOST 'echo "SSH connection successful"'
    - scp app/leomail-backend/target/${APP_NAME}.jar $SSH_USER@$SSH_HOST:/home/$SSH_USER/
    # Deploy the application
    - ssh $SSH_USER@$SSH_HOST 'pkill -f ${APP_NAME}.jar || true'
    - ssh $SSH_USER@$SSH_HOST "nohup java -jar /home/$SSH_USER/${APP_NAME}.jar &"
  only:
    - dev
